// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-actualites.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.4";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-actualites.ts
var list_actualites_default = defineTool({
  name: "list_actualites",
  title: "Lister les actualit\xE9s",
  description: "Liste les actualit\xE9s de la commune, les plus r\xE9centes d'abord. Recherche optionnelle par mot-cl\xE9 dans le titre.",
  inputSchema: {
    search: z.string().trim().optional().describe("Mot-cl\xE9 recherch\xE9 dans le titre."),
    limit: z.number().int().min(1).max(50).optional().describe("Nombre maximum d'actualit\xE9s (d\xE9faut 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("actualites").select("id, titre, contenu, type, auteur, image_url, publie_le, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (search) query = query.ilike("titre", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { actualites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-evenements.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.23.8";
var list_evenements_default = defineTool2({
  name: "list_evenements",
  title: "Lister les \xE9v\xE9nements",
  description: "Liste les \xE9v\xE9nements de la commune. Par d\xE9faut seuls les \xE9v\xE9nements \xE0 venir sont renvoy\xE9s.",
  inputSchema: {
    include_past: z2.boolean().optional().describe("Inclure aussi les \xE9v\xE9nements d\xE9j\xE0 termin\xE9s (d\xE9faut false)."),
    limit: z2.number().int().min(1).max(50).optional().describe("Nombre maximum d'\xE9v\xE9nements (d\xE9faut 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_past, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("evenements").select(
      "id, titre, lieu, organisateur, date_debut, date_fin, heure_debut, heure_fin, contact1, contact2, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (!include_past) {
      query = query.gte("date_fin", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { evenements: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-offres-emploi.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.23.8";
var list_offres_emploi_default = defineTool3({
  name: "list_offres_emploi",
  title: "Lister les offres d'emploi",
  description: "Liste les offres d'emploi publi\xE9es sur l'application, les plus r\xE9centes d'abord. Recherche optionnelle par mot-cl\xE9 dans le titre.",
  inputSchema: {
    search: z3.string().trim().optional().describe("Mot-cl\xE9 recherch\xE9 dans le titre de l'offre."),
    limit: z3.number().int().min(1).max(50).optional().describe("Nombre maximum d'offres (d\xE9faut 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("offres_emploi").select("id, titre, employeur, description, localisation, type_contrat, publie_le, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (search) query = query.ilike("titre", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { offres: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-villages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.23.8";
var list_villages_default = defineTool4({
  name: "list_villages",
  title: "Lister les villages",
  description: "Liste les villages rattach\xE9s \xE0 la commune, avec leur description et leurs contacts. Recherche optionnelle par nom.",
  inputSchema: {
    search: z4.string().trim().optional().describe("Mot-cl\xE9 recherch\xE9 dans le nom du village."),
    limit: z4.number().int().min(1).max(100).optional().describe("Nombre maximum de villages (d\xE9faut 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("villages").select("id, nom, description, population, code_postal, contact, contact2, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.ilike("nom", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { villages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Mon profil",
  description: "Renvoie le profil de l'utilisateur connect\xE9 (nom, pr\xE9nom, commune, village d'origine, contact).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("users_profiles").select(
      "id, user_id, nom, prenom, contact_telephone, lieu_residence, lieu_naissance, commune_id, village_origine_id, created_at"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Aucun profil trouv\xE9 pour cet utilisateur." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/create-suggestion.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.23.8";
var create_suggestion_default = defineTool6({
  name: "create_suggestion",
  title: "Cr\xE9er une suggestion",
  description: "Publie une suggestion adress\xE9e \xE0 la mairie au nom de l'utilisateur connect\xE9. \xC9crit une nouvelle ligne dans l'application.",
  inputSchema: {
    titre: z5.string().trim().min(1).describe("Titre court de la suggestion."),
    contenu: z5.string().trim().min(1).describe("Contenu d\xE9taill\xE9 de la suggestion.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ titre, contenu }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: profile } = await supabase.from("users_profiles").select("nom, prenom").eq("user_id", ctx.getUserId()).maybeSingle();
    const auteur = [profile?.prenom, profile?.nom].filter(Boolean).join(" ").trim() || ctx.getUserEmail() || "Utilisateur";
    const { data, error } = await supabase.from("suggestions").insert({ titre, contenu, auteur }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { suggestion: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mmslqomfaeklpgmdpxcq";
var mcp_default = defineMcp({
  name: "ville-connectee",
  title: "ville-connectee",
  version: "0.1.0",
  instructions: "Outils de l'application communautaire Ville Connect\xE9e : consulter les actualit\xE9s, les \xE9v\xE9nements, les offres d'emploi et les villages, lire le profil de l'utilisateur connect\xE9 et publier une suggestion \xE0 la mairie. Les donn\xE9es sont lues au nom de l'utilisateur connect\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_actualites_default,
    list_evenements_default,
    list_offres_emploi_default,
    list_villages_default,
    get_my_profile_default,
    create_suggestion_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
