// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmslqomfaeklpgmdpxcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tc2xxb21mYWVrbHBnbWRweGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDAzMDAsImV4cCI6MjA2MDgxNjMwMH0.FnB9O8qqE_V1n-SEJTk17VcwwmvRJeh5Dr-vdirI8zE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);